#端口号
server:
  port: 8088
  servlet:
    context-path: /springbootdemo
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp


---
spring:
  profiles: development

  #jdbc
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cjylocaldatabase?useUnicode=true&characterEncoding-UTF-8
    username: root
    password: root1234
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.springbootdemo.entity
  mapper-locations: classpath*:com/springbootdemo/mapper/*.xml
  config-location: classpath:/mybatis-config.xml





---
spring:
  profiles: test
---
spring:
  profiles: production